# nginx에서 제대로 매핑할 수 있게 하기 위해, swagger api 역시 /api/v1 하에서 동작해야 한다
springdoc:
  swagger-ui:
    path: /api/v1/swagger-ui

spring:
  application:
    name: mutualrisk

  datasource:
    url: jdbc:mysql://j11a607.p.ssafy.io:3306/product?useUnicode=true&characterEncoding=UTF-8
    username: ssafy
    password: zeroticket607
    driver-class-name: com.mysql.cj.jdbc.Driver
    maximum-pool-size: 150
    minimum-idle: 60
    connection-timeout: 10000
    connection-init-sql: SELECT 1
    idle-timeout: 600000
    max-lifetime: 1800000
    auto-commit: true

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  devtools:
    restart:
      additional-paths: .

  data:
    redis:
      host: redis
      port: 6379

    mongodb:
      uri: mongodb://ssafy:zeroticket607@j11a607.p.ssafy.io:27017/
      database: product

  logging.level:
    org.hibernate.SQL: debug

  jwt:
    secret-key: Z29nby10bS1zZXJ2ZXItZGxyamVvYW9yb3JodG9kZ290c3Atam9vbmdhbmduaW0teWVvbHNpbWhpaGFswvuqoxyve

  oauth:
    kakao:
      client-id: ddd1cb07e0545f2d743ebe394aae68fa
      redirect_uri : https://j11a607.p.ssafy.io/login/kakao/callback
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
      client-secret: ZlyVJxR6mF3RnLWh0kEDHazxeuQdiQe3
      scope: profile_nickname,profile_image, account_email

  mail:
    host: smtp.gmail.com
    port: 587
    username: sujipark2009@gmail.com
    password: waqo zlvt olao pwli
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true